id: P003267
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG18765
  title: ཞ་རྣམ་བྲ་གསུམ་གྱི་སུམ་རྟགས་འགྲེལ་པ་ཕྱོགས་བསྒྲིགས་མུན་སེལ་སྒྲོན་མེ།
  author: ''
  volumes:
    f14208c10f384861a0654376abc8c23f:
      image_group_id: I1KG20611
      title: ''
      volume_number: 1
      total_pages: 302
      base_file: v001.txt
