id: IFD17FC5B
legacy_id: P003267
ocr_import_info:
  bdrc_scan_id: W1KG18765
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T11:11:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:41:22.209259+00:00'
last_modified: 2022-08-27 14:41:54.387551
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG18765
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG18765
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞ་རྣམ་བྲ་གསུམ་གྱི་སུམ་རྟགས་འགྲེལ་པ་ཕྱོགས་བསྒྲིགས་མུན་སེལ་སྒྲོན་མེ།
  author: པྲ་ཏི་དགེ་བཤེས་རིན་ཆེན་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9104344216472511
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG20611:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20611
      total_pages: 302
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG20611.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9104344216472511
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
